### ISSUE TITLE
Saving the reduced model

### ISSUE THREAD

**Issue by Mikkolehtimaki** [orena1/neuron_reduce#10]
Hello,

I would like to inquire what are my possibilities with regards to saving the reduced model? Is the only option pickling the output from `subtree_reductor` and later loading it in python, or is it possible to save the model in a format that can be later opened in NEURON?

Thanks in advance!

**Comment by orena1** [comment]
Hello @Mikkolehtimaki  as far as I know there is no direct way to save neuronal models in NEURON (reduced or detailed).  @asanin-epfl had some experience with saving reduced models, maybe he can help?

**Comment by asanin-epfl** [comment]
This might be a very complicated topic, depending on your needs. For saving morphology you can use a project https://github.com/JustasB/hoc2swc. For biophysics it is tightly coupled to your context.

**Comment by Mikkolehtimaki** [comment]
I see, thank you for the insight! We also had trouble with pickling, seems that `Vector` cannot be pickled.
