### ISSUE TITLE
Replace `print` statements with `logging`

### ISSUE THREAD

**Issue by asanin-epfl** [orena1/neuron_reduce#11]
During circuit reduction the output of `neurond_reduce` seriously swamps other output. Would it be ok if I replace `print` statements with `logging` functionality? I have around 200 KB of such output:
```
There is no segment to segment copy, it means that some segments in the reduce...
```

**Comment by asanin-epfl** [comment]
Great, I will implement it then.

**Comment by orena1** [comment]
That would be great, thank you

**Comment by asanin-epfl** [comment]
@orena1 Can you please release a new version on pypi, so I can anchor to it?
Thank you.
