### ISSUE TITLE
Quick question to confirm. Does reduction always collapse neurite to a single section?

### ISSUE THREAD

**Issue by asanin-epfl** [orena1/neuron_reduce#12]
Hello! Can you please confirm or reject my question? Is it correct to state that reduction always collapses a neurite to a single NEURON [Section](https://www.neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/topology.html#Section) (with possible multiple compartments/nseg) no matter how huge this neurite is?
So the situation when one basal section connects to another basal section is impossible. Do they always connect to soma?

**Comment by orena1** [comment]
Yes, that is correct

**Comment by asanin-epfl** [comment]
Thank you so much for the fast response!
