### ISSUE TITLE
unneeded gui import

### ISSUE THREAD

**Issue by a1eko** [orena1/neuron_reduce#3]
Is importing gui in 'subtree_reductor_func.py' really needed?

**Comment by orena1** [comment]
See this
https://github.com/orena1/neuron_reduce/pull/1#discussion_r291061063

I assume it can be removed if we load the needed hoc files using load_file("...").
It there a problem with import the gui?

**Comment by a1eko** [comment]
Well, if one imports neuron_reduce in jupyter notebook, a GUI windows pops up. This is kind of ugly since it's not expected.

**Comment by orena1** [comment]
Ok, I'll try to see if I can remove it.

**Comment by orena1** [comment]
Fixed with https://github.com/orena1/neuron_reduce/commit/8519186cc00f715de8cab69060b19d2afd78ab4b
