### ISSUE TITLE
Question about reduction of source cells (Outcome synapses)

### ISSUE THREAD

**Issue by asanin-epfl** [orena1/neuron_reduce#5]
Hi! I understand this situation is improbable but I think it might exists in practice. An example:

```python
from neuron import h

h.load_file('L5PCtemplate.hoc')
source_cell = h.L5PCtemplate('cell1.asc')
target_cell = h.L5PCtemplate('cell1.asc')
synapse = h.Exp2Syn(target_cell.apical[12](0.5))
netcon = h.NetCon(
    source_cell.axon[6](0.5),
    synapse)
```
Everything is going to be fine when we reduce `target_cell`. We get a reduced location for `synapse` and update its location. The question is how should we proceed if `source_cell` is reduced? We need to update the source location of `netcon`. How would you suggest to handle this? Is it an impossible situation in real neuroscience simulations?

**Comment by orena1** [comment]
Hi @asanin-epfl  it is indeed a possible situation, it is called Dendrodendritic synapse. This problem will also arise when we will need to reduce cells with Gap Junctions (though in this case, I am not sure a general solution will be possible)

I think it is possible to handle this problem by adding another feature to the subtree_reductor function, so it will also return the deatiled_segment-to-reduced_segment mapping. This mapping can then be used manually to map the new location on the NetCons.

What do you think?

**Comment by asanin-epfl** [comment]
The mapping solution looks good to me.

**Comment by orena1** [comment]
Hi, I think that this patch:
https://github.com/orena1/neuron_reduce/pull/6/commits/01fb59a72f17b8ecb52090d307510532f9456748

 add the feature that we discussed:
