### ISSUE TITLE
Question about model.hoc

### ISSUE THREAD

**Issue by asanin-epfl** [orena1/neuron_reduce#8]
Do I need to use `geom_nseg()`, `biophys()` of the default *model.hoc* in my *custom.hoc* If I use the latter as `model_template`?
```python
neuron_reduce.subtree_reductor(...,model_filename='custom.hoc')
```

**Comment by orena1** [comment]
Hi @asanin-epfl  you can use a custom hoc file (custom.hoc) but you should do it knowledgeably. For example, usually, the biophys() is responsible for channel distribution. _Neuron_Reduce_ already copy the channels (with respect to the transfer resistance) so this function should be empty and not change the channel distribution.
