### ISSUE TITLE
Question about `total_segments_manual` argument

### ISSUE THREAD

**Issue by asanin-epfl** [orena1/neuron_reduce#9]
Can you please clarify about `total_segments_manual` argument of `subtree_reductor`. I need to better understand it.
I have a cell with 11 synapses. During the reduction in method `merge_and_add_synapses` at this [line](https://github.com/orena1/neuron_reduce/blob/master/neuron_reduce/subtree_reductor_func.py#L692) they receive the next positions (offset + section segment):
```
  0.032426184821815696 model[0].dend[0]
  0.032426184821815696 model[0].dend[0]
  0.012948382704962572 model[0].dend[1]
  0.10025492308704999 model[0].dend[2]
  0.10025492308704999 model[0].dend[2]
  0.10224592355734784 model[0].dend[3]
  0.059093705516716 model[0].dend[5]
  0.059093705516716 model[0].dend[5]
  0.09401371780768385 model[0].dend[5]
  0.4519636798941064 model[0].dend[5]
  0.3752090096168105 model[0].dend[5]
```
Later when I access those synapses in NEURON they have different positions because segmentation of sections is very low and all these very precise offsets like `0.032426184821815696` turn into very different offsets like `0.1`. What would you suggest in this situation in order to preserve original offsets as much as possible? Below I put how changed the above positions
```
0.1 model[0].dend[0]
0.1 model[0].dend[0]
0.1 model[0].dend[1]
0.1 model[0].dend[2]
0.1 model[0].dend[2]
0.16666 model[0].dend[3]
0.1 model[0].dend[5]
0.1 model[0].dend[5]
0.1 model[0].dend[5]
0.5 model[0].dend[5]
0.3 model[0].dend[5]
```

**Comment by orena1** [comment]
Hi,
It depends on the number of segments in each section of the reduced model. See slide 9 here:
https://github.com/orena1/NEURON_tutorial/blob/master/NEURON_tutorial.pptx
I do not think that it is possible to extract the original location that the synapse was added to after it was put inside a segment.
But the higher the number that you set in total_segments_manual to the more exact location you will get. But it will make the reduction process longer. 

In relation to the segmentation, how do you save the reduced model? Is the number of segments in each section also saved?

**Comment by orena1** [comment]
Hi @asanin-epfl , can I close the ticket?
